# Generated by Django 3.1.3 on 2020-12-09 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
                ('Grade', models.CharField(max_length=100)),
                ('Major', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Final_P1.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerFavoriteCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_char', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Final_P1.player')),
            ],
        ),
    ]
